export const AUTH_LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST'
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS'
export const AUTH_LOGIN_FAILED = 'AUTH_LOGIN_FAILED'

export const BOOKS_REQUEST = 'BOOKS_REQUEST'
export const BOOKS_MY_FOUND = 'BOOKS_MY_FOUND'
export const BOOKS_MY_ADDED = 'BOOKS_MY_ADDED'
export const BOOKS_FAILED = 'BOOKS_FAILED'